### ISSUE TITLE
Why not MIT license?

### ISSUE THREAD

**Issue by GeorgeS2019** [RyanRemer/MarchingCubesGodot#1]

**Comment by RyanRemer** [comment]
Could you give more context to your question? Why should I change to an MIT license?

**Comment by GeorgeS2019** [comment]
I contribute to some Microsoft'S dotnet projects.
First requirement for considering 3rd party library is that it MUST BE MIT license to be compatible with Microsoft dotnet MIT license openness.

**Comment by RyanRemer** [comment]
It looks like Godot also uses an MIT license itself, I'll update the license thanks!
